image: microsoft/dotnet-preview

stages:
  - build
  - connect
  - test

services:
  - postgres:latest

variables:
  POSTGRES_USER: "pgsqlclient"
  POSTGRES_PASSWORD: "pgsqlclient"
  POSTGRES_NORTHWIND_DB: "northwind"
  POSTGRES_PUBS_DB: "pubs"

connect:
  image: postgres
  script:
  # northwind
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - createdb -h "postgres" -U "$POSTGRES_USER" -O "$POSTGRES_USER" $POSTGRES_NORTHWIND_DB
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_NORTHWIND_DB" -f PostgreSql.Data.SqlClient.Tests/Resources/northwind.sql
  # pubs
  - createdb -h "postgres" -U "$POSTGRES_USER" -O "$POSTGRES_USER" $POSTGRES_PUBS_DB
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_PUBS_DB" -f PostgreSql.Data.SqlClient.Tests/Resources/pubs.sql

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build PostgreSql.Data.SqlClient PostgreSql.Data.SqlClient.Tests

test:
  stage: test
  script:
    - cd PostgreSql.Data.SqlClient.Tests
    - mv ConnectionString.ci.xml ConnectionString.xml
    - dotnet test
