image: microsoft/dotnet-nightly:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd src/PostgreSql.Data.SqlClient
    - dotnet restore --verbosity:q
    - dotnet build -c Debug
    - dotnet build -c Release
    - cd .. && cd ..
    - cd tests/PostgreSql.Data.SqlClient.Tests
    - dotnet restore --verbosity:q
    - dotnet build -c Debug
    - dotnet build -c Release

test:
  stage: test
  services:
    - postgres:latest
  before_script:
    - apt-get update -y -qq
    - apt-get install postgresql-client -y -qq
    # northwind
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - createdb -h "postgres" -U "$POSTGRES_USER" -O "$POSTGRES_USER" $POSTGRES_NORTHWIND_DB
    - psql -q -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_NORTHWIND_DB" -f tests/PostgreSql.Data.SqlClient.Tests/Resources/northwind.sql
    # pubs
    - createdb -h "postgres" -U "$POSTGRES_USER" -O "$POSTGRES_USER" $POSTGRES_PUBS_DB
    - psql -q -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_PUBS_DB" -f tests/PostgreSql.Data.SqlClient.Tests/Resources/pubs.sql
    # project setup
    - mv tests/PostgreSql.Data.SqlClient.Tests/ConnectionString.ci.xml tests/PostgreSql.Data.SqlClient.Tests/ConnectionString.xml
  script:
    - cd tests/PostgreSql.Data.SqlClient.Tests
    - dotnet restore --verbosity:q
    - dotnet build
    - dotnet test
