image: microsoft/dotnet-preview:latest

stages:
  - build
  - test

# services:
#   - postgres:latest

variables:
  POSTGRES_USER: "pgsqlclient"
  POSTGRES_PASSWORD: "pgsqlclient"
  POSTGRES_NORTHWIND_DB: "northwind"
  POSTGRES_PUBS_DB: "pubs"

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build -c Debug src/PostgreSql.Data.SqlClient tests/PostgreSql.Data.SqlClient.Tests
    - dotnet build -c Release src/PostgreSql.Data.SqlClient tests/PostgreSql.Data.SqlClient.Tests

test:
  stage: test
  services:
    - postgres:latest
  before_script:
    - apt-get update -y
    - apt-get install postgresql-client -y
    # northwind
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - createdb -h "postgres" -U "$POSTGRES_USER" -O "$POSTGRES_USER" $POSTGRES_NORTHWIND_DB
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_NORTHWIND_DB" -f tests/PostgreSql.Data.SqlClient.Tests/Resources/northwind.sql
    # pubs
    - createdb -h "postgres" -U "$POSTGRES_USER" -O "$POSTGRES_USER" $POSTGRES_PUBS_DB
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_PUBS_DB" -f tests/PostgreSql.Data.SqlClient.Tests/Resources/pubs.sql
  script:
    - mv tests/PostgreSql.Data.SqlClient.Tests/ConnectionString.ci.xml tests/PostgreSql.Data.SqlClient.Tests/ConnectionString.xml
    - dotnet restore
    - dotnet build src/PostgreSql.Data.SqlClient tests/PostgreSql.Data.SqlClient.Tests
    - cd tests/PostgreSql.Data.SqlClient.Tests
    - dotnet test
