image: microsoft/dotnet:1.0.0-preview2-sdk

stages:
  - build
  - test

build:
  stage: build
  script:
    - export DOTNET_CLI_TELEMETRY_OPTOUT=1
    - dotnet restore
    - dotnet build -c Debug **/project.json
    - dotnet build -c Release **/project.json

test:
  stage: test
  services:
    - postgres:latest
  before_script:
    - apt-get update -y -qq
    - apt-get install postgresql-client -y -qq
    # northwind
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - createdb -h "postgres" -U "$POSTGRES_USER" -O "$POSTGRES_USER" $POSTGRES_NORTHWIND_DB
    - psql -q -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_NORTHWIND_DB" -f tests/PostgreSql.Data.SqlClient.Tests/Resources/northwind.sql
    # pubs
    - createdb -h "postgres" -U "$POSTGRES_USER" -O "$POSTGRES_USER" $POSTGRES_PUBS_DB
    - psql -q -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_PUBS_DB" -f tests/PostgreSql.Data.SqlClient.Tests/Resources/pubs.sql
    # project setup
    - mv tests/PostgreSql.Data.SqlClient.Tests/ConnectionString.ci.xml tests/PostgreSql.Data.SqlClient.Tests/ConnectionString.xml
    - dotnet restore --verbosity Error
  script:
    - dotnet build **/project.json
    - cd tests/PostgreSql.Data.SqlClient.Tests
    - dotnet test
